# Generated by Django 2.2.6 on 2019-11-15 15:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trans_type', models.CharField(max_length=254)),
                ('trans_establishment', models.CharField(max_length=254)),
                ('trans_amt', models.IntegerField()),
                ('trans_date', models.DateField()),
                ('purpose', models.CharField(max_length=254)),
                ('attendees', models.ManyToManyField(blank=True, to='api.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_user', to='api.User')),
            ],
        ),
    ]
